<a href="https://colab.research.google.com/github/maynak-dev/Machine-Learning/blob/main/Complete_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy - Numerical Python

**Advantages of NumPy Arrays - **
1. Allows Several Mathematical Operations
2. Faster Operations




In [ ]:
import numpy as np

In [ ]:
# List vs. NumPy - Time Taken
from time import process_time

In [ ]:
# Time taken by a List
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0005446679999998594


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00016821499999997158


**NumPy Arrays**

In [ ]:
#normal list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
#NumPy Arrays
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# Creating 1D array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape #detect number of rows and columns

(4,)

In [ ]:
# Creating a 2D array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c= np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


**Initial Placeholders in NumPy arrays**

In [ ]:
# Creating a NumPy arrays of Zeros
x = np.zeros((4,5)) # 4--> Rows and 5--> Columns
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Creating a Numpy Arrays of Ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Creating a NumPy arrays of Specific values
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# Creating an Identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Creating a NumPy arrays with random values
b = np.random.random((3,4))
print(b)

[[0.98394025 0.33425363 0.0723395  0.24609428]
 [0.07749598 0.75631516 0.10532563 0.35720312]
 [0.4396192  0.9047366  0.62058137 0.00591033]]


In [ ]:
# Random Integer values array with a specific range
c = np.random.randint(10,100,(3,4))  # 3 X 4 matrix of random integer numbers between 10 to 100
print(c)

[[33 13 99 53]
 [78 93 81 29]
 [60 98 43 34]]


In [ ]:
# Array of Evenly spaced values
d = np.linspace(10,30,5)  # We need 5 evenly spaced values between 10 to 30
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
e = np.arange(10,30,5)  #we need the gap between numbers would be 5 between range 10 to 30
print(e)

[10 15 20 25]


In [ ]:
# Convert a list to a numpy array
list2 = [10,20,20,20,50]
print(list2)
print(type(list2))
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10, 20, 20, 20, 50]
<class 'list'>
[10 20 20 20 50]


numpy.ndarray

In [ ]:
#Finding dimension of the array
print(c.ndim)

2


In [ ]:
#number of elements in an array
print(c.size)

12


In [ ]:
#checking the datatype
print(c.dtype)

int64


**Mathematical Operations on np array**

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2) #Concatenation

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[2 7 0]
 [7 9 9]
 [7 3 4]]
[[17 10 12]
 [19 12 13]
 [10 16 15]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[19 17 12]
 [26 21 22]
 [17 19 19]]
[[-15  -3 -12]
 [-12  -3  -4]
 [ -3 -13 -11]]
[[ 34  70   0]
 [133 108 117]
 [ 70  48  60]]
[[0.11764706 0.7        0.        ]
 [0.36842105 0.75       0.69230769]
 [0.7        0.1875     0.26666667]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[9 5 8]
 [9 9 1]
 [6 5 4]]
[[17 15 19]
 [14 15 14]
 [13 15 16]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[26 20 27]
 [23 24 15]
 [19 20 20]]
[[ -8 -10 -11]
 [ -5  -6 -13]
 [ -7 -10 -12]]
[[153  75 152]
 [126 135  14]
 [ 78  75  64]]
[[0.52941176 0.33333333 0.42105263]
 [0.64285714 0.6        0.07142857]
 [0.46153846 0.33333333 0.25      ]]


**Array Manipulation**

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
array.shape

[[8 0 7]
 [2 0 5]]


(2, 3)

In [ ]:
# Transpose of Array
trans = np.transpose(array)
print(trans)
trans.shape

[[8 2]
 [0 0]
 [7 5]]


(3, 2)

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
array.shape

[[7 2 7]
 [7 5 3]]


(2, 3)

In [ ]:
trans2 = array.T
print(trans2)
trans2.shape

[[7 7]
 [2 5]
 [7 3]]


(3, 2)

In [ ]:
#Reshaping an Array
arr = np.random.randint(0,10,(2,3))
print(arr)
arr.shape

[[4 4 3]
 [9 6 4]]


(2, 3)

In [ ]:
barr = arr.reshape(3,2)
print(barr)
barr.shape

[[4 4]
 [3 9]
 [6 4]]


(3, 2)